version: '3'

services:
    web:
        image: d4n13l301/web3-ri2024-guantay:latest
        ports:
            - "8080:80"
        volumes:
            - ./web/file:/usr/share/nginx/html/file
        networks:
            - code-network
networks:
  code-network:
    driver: bridge
